### ISSUE TITLE
Unify the use of the correct bitvector

### ISSUE THREAD

**Issue by DerFred3** [EdgeGnW/RustPraxisProjekt2024#37]
The wavemodel transformation uses the ```sucds::BitVector``` whereas the ```get_bitmap``` (<- needs to be changed to 'to_bitmap') function inside of the GraphModel uses the ```sucds::Rank9Sel``` data type.

**Comment by EdgeGnW** [comment]
only the sucds::Rank9Sel data type allows for O(1) access and rank and O(log u) select queries

**Comment by DerFred3** [comment]
merged
